[tool.poetry]
name = "slack"
version = "0.1.0"
description = ""
authors = ["NikeNano <niklas.sven.hansson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
slackclient = "^2.9.3"
slack-sdk = "^3.15.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
