apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-parameter-
spec:
  entrypoint: output-parameter
  templates:
  - name: output-parameter
    steps:
    - - name: generate-json
        template: whalesay
    - - name: consume-parameter
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-json.outputs.parameters.hello-param}}"
    - - name: publish-to-slack
        template: slack-integration
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-json.outputs.parameters.hello-param}}"

  
  - name: whalesay
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import os

        filename = "/tmp/hello_world.txt"
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "w") as fp:
          json.dump({"channel": "C035Q8CELGM", "text": "Hello Niklas"}, fp)
    outputs:
      parameters:
      - name: hello-param
        valueFrom: 
          path: /tmp/hello_world.txt
  
  - name: slack-integration
    inputs:
      parameters:
      - name: message
    plugin:
      test: "{{inputs.parameters.message}}"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]