apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-parameter-
spec:
  entrypoint: output-parameter
  templates:
  - name: output-parameter
    steps:
    - - name: generate-json
        template: whalesay
    - - name: consume-parameter
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-json.outputs.parameters.hello-param}}"
    - - name: publish-to-slack
        template: slack-integration
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-json.outputs.parameters.hello-param}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo -n \'{\"channel\": \"test\", \"text\": \"Hello Niklas\"}\' > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom: 
          path: /tmp/hello_world.txt
  
  - name: slack-integration
    inputs:
      parameters:
      - name: message
    plugin:
      hello: "{{inputs.parameters.message}}"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]