apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: goofy-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        test: |
          {
            "test":"values"
            "more":"some sweet input"
          }
    - name: whalesay            # Defining the "whalesay" template
      container:
        image: docker/whalesay
        command: [sleep]
        args: ["2000"]
