apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: goofy-
spec:
  ttlStrategy:
    secondsAfterCompletion: 500  # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 500     # Time to live after workflow is successful
    secondsAfterFailure: 500     # Time to live after workflow fails
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: |
          {
            "channel": "test",
            "text": "Hello Niklas"
          }
